name: brl_to_usd_flutter
description: Conversor simples BRL -> USD
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.19.0
  http: ^1.6.0
flutter:
  uses-material-design: true